include = ["pyproject.toml", "packages/**/*.py", "scripts/**/*.py"]
line-length = 120
target-version = "py312"

[lint]
extend-ignore = [
  "D100",  # Missing docstring in public module
  "D104",  # Missing docstring in public package
]
ignore = [
  "W191",  # indentation contains tabs
  "D401",  # imperative mood
  "RUF001",  # ambiguous unicode char in string (中文全角标点属正常)
  "RUF002",  # ambiguous unicode char in docstring (中文全角标点属正常)
  "RUF003"  # ambiguous unicode char in comment (中文全角标点属正常)
]
select = [
  "E",  # pycodestyle errors
  "W",  # pycodestyle warnings
  "F",  # pyflakes
  "I",  # isort
  "B",  # flake8-bugbear
  "C4",  # flake8-comprehensions
  "D",  # pydocstyle
  "UP",  # pyupgrade
  "RUF",  # Ruff-specific rules
  "SIM",  # flake8-simplify
  "PLC0415"  # import should be at top-level of file
]

[lint.isort]
force-single-line = true
lines-after-imports = 2

[lint.pydocstyle]
convention = "google"
